### ISSUE TITLE
D855 16gb

### ISSUE THREAD

**Issue by Fearup** [xNNism/LG-G3_Nethunter#1]
hi, i have the 16GB version do you think it will cause problems if i flash this ? i have a tp-link tl-wn722n wifi adapter will it work ?

**Comment by xNNism** [comment]
As long as you have enough free space left on your internal storage, i don't think there will be any problems, although  i recommend to make a backup.
TL-WN722n is testet and working as intended.

**Comment by Fearup** [comment]
Thanks for the info glad to hear that its working.Soo do i need to flash the kernel and the kalifs-full or just kalifs-full ? i got confused it only says  flash Nethunter-LGD855_CM.zip. you should make a thread on xda a lot of people want this

**Comment by xNNism** [comment]
You only have to flash the whole .zip in TWRP. The Kernel flashing, installation and the chroot-process are fully automated in all three builds. After flashing the zip don't forget to flash the  Sharpening-Mod, otherwise its possible to bootloop the device

As soon as i solve the problem with the "Bad-USB" and patched some minor Bugs like the bootanimation, i'll create a Thread on XDA  :)

**Comment by Fearup** [comment]
just Flashed working fine LG G3 D855 16GB

**Comment by Fearup** [comment]
When i disconnect the TL-WN722n the phone reboots no mather what i do ifconfig wlan1 down dosent help other than that it works perfectly

**Comment by xNNism** [comment]
Allright, nice to hear and thanks for testing. So far im sure It should work for all G3 variants with the Qualcomm MSM8974AC.
